IF EXISTS (SELECT * FROM sys.database_principals WHERE name = 'MANAGED-IDENTITY')
BEGIN
    DROP USER [MANAGED-IDENTITY];
END
GO
CREATE USER [MANAGED-IDENTITY] FROM EXTERNAL PROVIDER;
GO
ALTER ROLE db_datareader ADD MEMBER [MANAGED-IDENTITY];
ALTER ROLE db_datawriter ADD MEMBER [MANAGED-IDENTITY];
GRANT EXECUTE TO [MANAGED-IDENTITY];
GO
